-- Create the different workouts for the app

-- CHEST
	-- name, discription, primrary muscle group 
		-- muscle group is needed to help group the different exersices 
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Bench Press","Lay down on a bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.","chest", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Push Up","Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.","chest", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Dumbbell Flyes","Take two dumbbells and lay on a bench, make sure the feet are firmly on the ground and your back is not arched, but has good contact with the bench. The arms are stretched in front of you, about shoulder wide. Bend now the arms a bit and let them down with a half-circle movement to the side. Without changing the angle of the elbow bring them in a fluid movement back up.","chest", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Incline Dumbbell Press","The movement is very similar to benchpressing with a barbell, however, the weight is brought down to the chest at a lower point. Hold two dumbbells and lay down on a bench. Hold the weights next to the chest, at the height of your nipples and press them up till the arms are stretched. Let the weight slowly and controlled down.","chest", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Cable Cross Over","Begin with cables at about shoulder height, one in each hand. Take a step forward so that one foot is in front of the other, for stability, and so that there is tension on the cables. Bring hands together in front of you. Try to make your hands overlap (so that the cables cross) a few inches.","chest", NOW(), NOW());

-- UPPER BACK 
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Bent Over Row","Back excercise with a barbell with a starting position which is in a bent over position with the back paralell to the ground. The barbell is on the ground at chest level.For the movement grab the barbell at shoulder width grip and pull towards your chest without losing the bent over position and without moving anything but your arms","upper_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("One Arm Row","Assume a standing position while holding a dumbbell in one hand with a neutral grip. Hinge forward until your torso is roughly parallel with the floor (or slightly above) and then begin the movement by driving the elbow behind the body while retracting the shoulder blade. Pull the dumbbell towards your body until the elbow is at (or just past) the midline and then slowly lower the dumbbell back to the starting position under control. Repeat for the desired number of repetitions on both sides.","upper_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Reverse Flyes"," When lying face down and using dumbbells, a person holds a dumbbell in each hand. With your elbows slightly bent, slowly lift the weights to where the hands reach shoulder level or a little before shoulder level. You should feel tension or a pinch in the upper back when you have reached the shoulder position. Then, lower the weights back to the floor. If you perform this exercise while upright, lift from the waist, then lift the barbells from the waist level backward (a typical fly moves the weights forward).","upper_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Axe Chops","N/A","upper_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Seated Cable Row","Set the appropriate weight on the weight stack and attach a close grip bar or V-bar to the seated row machine. Grasp the bar with a neutral grip (palms facing in). Keeping your legs slightly bent and your back straight, pull the weight up slightly off the stack. You should be sitting straight upright with your shoulders back. This is the starting position. Keeping your body in position, pull the handle into your stomach. Pull your shoulder blades back, squeeze, pause, and then slowly lower the weight back to the starting position. Repeat for desired reps.","upper_back", NOW(), NOW());

-- LOWER BACK 
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Deadlift","Stand firmly, with your feet slightly more than shoulder wide apart. Stand directly behind the bar where it should barely touch your shin, your feet pointing a bit out. Bend down with a straight back, the knees also pointing somewhat out. Grab the bar with a shoulder wide grip, one underhand, one reverse grip. Pull the weight up. At the highest point make a slight hollow back and pull the bar back. Hold 1 or 2 seconds that position. Go down, making sure the back is not bent. Once down you can either go back again as soon as the weights touch the floor, or make a pause, depending on the weight.","lower_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Lat Pull Downs","Pull bar down to strenum and keep straight back.","lower_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Superman","Lay flat on your stomach with your arms extended in front of you on the ground as your legs are lying flat. Lift both your arms and legs at the same time, as if you were flying, and contract the lower back. Make sure that you are breathing and, depending on your fitness level, hold the movement for at least two to five seconds per repetition.","lower_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Chin Ups","Like pull-ups but with a reverse grip","lower_back", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Pull Ups","Grab the pull up bar with a wide grip, the body is hanging freely. Keep your chest out and pull yourself up till your chin reaches the bar or it touches your neck, if you want to pull behind you. Go with a slow and controlled movement down, always keeping the chest out.","lower_back", NOW(), NOW());

-- ARMS
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Bicep Curls","Hold the Barbell shoulder-wide, the back is straight, the shoulders slightly back, the arms are streched. Bend the arms, bringing the weight up, with a fast movement. Without pausing, let down the bar with a slow and controlled movement.","arms", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Hammer Curls","Hold two dumbbells and sit on a bench with a straight back, the shoulders are slightly rolled backwards. Your pals point to your body. Bend the arms and bring the weight up with a fast movement. Don't rotate your hands, as with the curls. Without any pause bring the dumbbell down with a slow, controlled movement.","arms", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Dips","Hold onto the bars at a narrow place (if they are not parallel) and press yourself up, but don't stretch the arms completely, so the muscles stay during the whole exercise under tension. Now bend the arms and go down as much as you can, keeping the elbows always pointing back, At this point, you can make a short pause before repeating the movement.","arms", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Skullcrusher","Hold the dumbbells and lay down on a flat bench in such a way that around 1/4 of your head is over the edge. Stretch your arms with the weights and bend them so that the dumbbells are lowered (make sure they don't touch each other). Just before they touch your forehead, push them up.","arms", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Cable Pull Downs","Grab the cable, stand with your feet shoulder wide, keep your back straight and lean forward a little. Push the bar down, making sure the elbows don't move during the exercise. Rotate your hands outwards at the very end and go back to the initial position without pause.","arms", NOW(), NOW());

-- SHOULDERS
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Military Press","The military press is a variation of the overhead press weight training exercise using very strict form and no pre-movement momentum.The military press targets the deltoid muscles in the shoulders as well as the triceps. Additionally, it works the core and legs, which the lifter uses to help stabilize the weight.The lift begins with the lifter standing and the barbell on the anterior deltoids. The lifter then raises the barbell overhead by pressing the palms of the hands against the underside of the barbell.","shoulders", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Lateral Raises","Raise your arms out to the sides until they're at shoulder level. Pause, then lower the weights back to the starting position.","shoulders", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Front Raises","The movement is to bring the arms up in front of the body to eye level and with only a slight bend in the elbow. This isolates the anterior deltoid muscle (front of the shoulder) and uses the anterior deltoid to lift the weight.","shoulders", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Shoulder Press","Sit on a bench, the back rest should be almost vertical. Take a barbell with a shoulder wide grip and bring it up to chest height. Press the weight up, but don't stretch the arms completely. Go slowly down and repeat.","shoulders", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Shrugs","Take a barbell and stand with a straight body, the arms are hanging freely in front of you. Lift from this position the shoulders as high as you can, but don't bend the arms during the movement. On the highest point, make a short pause of 1 or 2 seconds before returning slowly to the initial position.","shoulders", NOW(), NOW());

-- ABS 
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Sit Ups","Sit on a mat, your calves are resting on a bench, the knees make a right angle. Hold your hands behind your neck. Go now up with a rolling movement of your back, you should feel how the individual vertebrae lose contact with the mat. At the highest point, contract your abs as much as you can and hold there for 2 sec. Go now down, unrolling your back.","abs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Crunches","Lay down on your back a soft surface, the feet are on the floor. Ask a partner or use some other help (barbell, etc.) to keep them fixed, your hands are behind your head. From this position move your upper body up till your head or elbows touch your knees. Do this movement by rolling up your back.","abs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Leg Raises","Lay down on a bench and hold onto the recliner with your hands to keep you stable. Hold your legs straight and lift them till they make an angle of about 45°. Make a short pause of 1 sec. and go slowly down to the initial position. To increase the intensity you can make a longer pause of 7 sec. every 5th time.","abs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Plank","Get into a position on the floor supporting your weight on your forearms and toes. Arms are bent and directly below the shoulder. Keep your body straight at all times and hold this position as long as possible. To increase difficulty an arm or leg can be raised while performing this exercise.  ","abs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Ab Twists","First, one should sit on the floor with knees bent as in a 'sit-up' position. The feet should be kept together and slightly above the ground or put under a stable surface. The torso should be kept straight with the back kept off the ground at a 45 degree angle. Arms should be held together away from the body in a straight fashion and hands kept locked together like a ball or one can hold a weight to increase the difficulty. Next, the arms should be swung from one side to another in a twisting motion, with each swing to a side counting as one repetition.","abs", NOW(), NOW());

-- BUTT
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Kick Backs","Kneel on floor with your hands placed about shoulder width apart. Point one arm out straight in front and extend the opposite leg to the rear. The shoulders and the hips should be parallel.","butt", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Kettlebell Swings","Hold the kettlebell securely in both hands. Keep your back flat throughout the move, avoiding any rounding of the spine.Keeping your knees 'soft', hinge your hips backwards, letting the kettlebell swing between your knees.","butt", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Glute Bridges","Lie on you back with your hips and knees flexed, feet on the ground. From this position, raise your butt off of the ground to a height where your body makes a straight line from your knees to your shoulders. To make the exercise more intense, you can add weight by letting a barbell rest on your hips as you complete the motion, or you can put your feet on a slightly higher surface such as a step or a bench.","butt", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Box Jumps","Squat down then jump up on to a box. Land soft on toes and transfer weight to heels","butt", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Hip Thrust","Sit on floor with long side of bench behind back. Roll barbell back and center over hips. Position upper back on corner of bench. Place feet on floor approximately shoulder width with knees bent. Grasp bar to each side.","butt", NOW(), NOW());

-- LEGS 
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Squat","Go now slowly down, till your thighs are parallel with the floor, not lower. The knees point outwards, your butt, out. Make a small pause of 1 second and with as much energy as you can, push the weight up. Make a pause of 2 seconds and repeat.","legs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Leg Extension","Take a deep breath and extend your legs as you flex your quadriceps. As you lock out the knees, exhale to complete the repetition. Slowly lower your feet back to the starting position and repeat for the desired number of repetitions.","legs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Lunges","Take two dumbbells in your hands, stand straight, feet about shoulder wide. Take one long step so that the front knee is approximately forming a right angle. The back leg is streched, the knee is low but doesn't touch the ground. 'Complete' the step by standing up and repeat the movement with the other leg.","legs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Leg Curls","Lay on a bench and put your calves behind the leg holder (better if they are hold on around the lower calves). Hold a grip on the bars to make sure the body is firmly in place. Bend your legs bringing the weight up, go slowly back. During the exercise the body should not move, all work is done by the legs.","legs", NOW(), NOW());
INSERT INTO allExercises (name, description, muscle_group, createdAt, updatedAt) VALUES("Calf Raises","Get onto the calf raises machine, you should able to completely push your calves down. Stand straight, don't make a hollow back and don't bend your legs. Pull yourself up as high as you can. Make a small pause of 1 - 2 seconds and go slowly down.","legs", NOW(), NOW());
